# Kustomization custom resources to load apps
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastracture-base
  namespace: flux-system
spec:
  interval: 1h
  path: ./infrastructure/base
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-environment
  namespace: flux-system
spec:
  interval: 1h
  path: ./infrastructure/production
  prune: true
  dependsOn:
    - name: infrastructure-base
  sourceRef:
    kind: GitRepository
    name: flux-system