apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - About Me:
        - Homelab Repository:
              href: https://github.com/Adrian-Covaciu/homelab
              icon: github.png
        - LinkedIn:
              href: https://www.linkedin.com/in/adrian-covaciu-57aa96147/
              icon: linkedin.png
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        # network: web
        uptime: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""