apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: web
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - homelab-acovaciu.go.ro
      secretName: homepage-tls
  rules:
    -  host: homelab-acovaciu.go.ro
       http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000